{% set name = "antarctic-plots" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antarctic_plots-{{ version }}.tar.gz
  sha256: 42bb6236e7d3b8dc07bc84450b05073791fe8a161362cc8226d8f83cd9f9d8a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - pandas
    - pooch
    - verde
    - xarray
    - pyproj
    - matplotlib-base
    - pyogrio
    - rioxarray
    - scipy
    - numpy
    - pygmt
    - geopandas
    - zarr
    - python-dotenv
    - pip

test:
  imports:
    - antarctic_plots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdtanker/antarctic_plots
  summary: Functions to automate Antarctic data visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdtanker
