{% set name = "antarctic-plots" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antarctic_plots-{{ version }}.tar.gz
  sha256: 5d56a1773c4c1ca5b27cf1caa1c95a20248fedeffb13292c9b6b21edb0b04ae2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - pandas
    - openpyxl
    - pooch
    - tqdm
    - verde>=1.8.0
    - xarray
    - pyproj
    - matplotlib
    - pyogrio
    - rioxarray
    - scipy
    - numpy
    - pygmt
    - geopandas
    - zarr
    - python-dotenv
    - nptyping

test:
  imports:
    - antarctic_plots

about:
  home: https://github.com/mdtanker/antarctic_plots
  summary: Functions to automate Antarctic data visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdtanker
